name: Nightly Deployment

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}
  EC2_SECURITY_GROUP: ${{ secrets.SECURITY_GROUP_ID }}
  EC2_SUBNET: ${{ secrets.SUBNET_ID }}
  EC2_KEY_NAME: ${{ secrets.EC2_KEY_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout infra repo
      uses: actions/checkout@v3

    - name: Clone application repo
      run: |
        git clone https://github.com/aailsaa/spa-app.git

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Build images
    - name: Build Docker images
      run: |
        bash scripts/build-image.sh

    # Launch temporary EC2
    - name: Launch temporary EC2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ${{ secrets.AMI_ID }} \
          --instance-type t2.micro \
          --security-group-ids $EC2_SECURITY_GROUP \
          --subnet-id $EC2_SUBNET \
          --associate-public-ip-address \
          --key-name $EC2_KEY_NAME \
          --user-data file://scripts/userdata.sh \
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

        aws ec2 wait instance-running --instance-ids $INSTANCE_ID

        EC2_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)

        echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

        echo "Temporary EC2 IP: $EC2_IP"

   # Set up ssh 
    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2-key.pem
        chmod 400 ec2-key.pem
        export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        export DB_URL=${{ secrets.DB_URL }}
        export DB_USER=${{ secrets.DB_USER }}
        export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

   # Wait for EC2
    - name: Wait for EC2 Initialization
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_IP \
        "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo waiting...; sleep 5; done"

    # Transfer images
    - name: Run containers on EC2
      run: |
        docker save spa-backend | ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_IP "sudo docker load"
        docker save spa-frontend | ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_IP "sudo docker load"
        
        scp -i ec2-key.pem -o StrictHostKeyChecking=no spa-app/docker-compose.deploy.yml ec2-user@$EC2_IP:docker-compose.yml

        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$EC2_IP << 'EOF'

        sudo docker compose up -d

        sudo docker ps
        sudo docker images
        sudo docker compose ps
        sudo docker compose logs --tail=50
        curl localhost:8080 || echo "Backend not responding yet"

        EOF

    # Smoke test
    - name: Smoke test
      run: |
        echo "Waiting for backend..."

        for i in {1..20}; do
          if curl -s http://$EC2_IP:8080 > /dev/null; then
            echo "Backend is up!"
            break
          fi
          echo "Waiting..."
          sleep 5
        done

        curl http://$EC2_IP:8080

    # Terminate temp EC2
    - name: Terminate temporary EC2
      if: always()
      run: |
        if [ -n "$INSTANCE_ID" ]; then
          aws ec2 terminate-instances --instance-ids $INSTANCE_ID
        fi

    # Push images to ECR
    - name: Push images to ECR
      run: |
        bash scripts/push-ecr.sh

    # Deploy to QA
    - name: Deploy to QA EC2
      run: |
        bash scripts/deploy-qa.sh
