name: Nightly Deployment

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}
  EC2_SECURITY_GROUP: ${{ secrets.SECURITY_GROUP_ID }}
  EC2_SUBNET: ${{ secrets.SUBNET_ID }}
  EC2_KEY_NAME: ${{ secrets.EC2_KEY_NAME }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout infra repo
      uses: actions/checkout@v3

    - name: Clone application repo
      run: |
        git clone https://github.com/aailsaa/spa-app.git

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Build images
    - name: Build Docker images
      run: |
        bash scripts/build-image.sh

    # Launch temporary EC2
    - name: Launch temporary EC2
      run: |
        bash scripts/create-ec2.sh
      env:
        AMI_ID: ${{ secrets.AMI_ID }}

   # Set up ssh 
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        cat <<EOF >> ~/.ssh/config
        Host *
          IdentityFile ~/.ssh/id_rsa
          StrictHostKeyChecking no
        EOF

    # Wait for EC2 
    - name: Wait for EC2 
      run: |
       echo "Waiting for EC2 SSH..."

       for i in {1..60}; do
         if ssh \
           -o BatchMode=yes \
           -o ConnectTimeout=3 \
           -o StrictHostKeyChecking=no \
           ec2-user@$EC2_IP "echo connected" >/dev/null 2>&1; then
      
           echo "EC2 is ready"
           exit 0
         fi
      
          echo "Attempt $i: not ready yet"
          sleep 5
        done
      
        echo "EC2 never became reachable"
        exit 1

    # Transfer images
    - name: Run containers on EC2
      run: |
        bash scripts/run-test-containers.sh
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    # smoke test
    - name: Smoke test
      run: |
        bash scripts/smoke-test.sh
      env:
        EC2_IP: ${{env.EC2_IP}}

    # Terminate temp EC2
    - name: Terminate temporary EC2
      if: always()
      run: |
        if [ -n "$INSTANCE_ID" ]; then
          aws ec2 terminate-instances --instance-ids $INSTANCE_ID
        fi

    # Push images to ECR
    - name: Push images to ECR
      run: |
        bash scripts/push-ecr.sh

    # Deploy to QA
    - name: Deploy to QA EC2
      run: | 
        bash scripts/deploy-qa.sh
      env:
        QA_EC2_IP: ${{ secrets.QA_EC2_IP }}
        ECR_REPO: ${{ secrets.ECR_REPO }}
