name: Nightly Deployment

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}
  EC2_SECURITY_GROUP: ${{ secrets.SECURITY_GROUP_ID }}
  EC2_SUBNET: ${{ secrets.SUBNET_ID }}
  EC2_KEY_NAME: ${{ secrets.EC2_KEY_NAME }}
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout infra repo
      uses: actions/checkout@v3

    - name: Clone application repo
      run: |
        git clone https://github.com/aailsaa/spa-app.git

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Build images
    - name: Build Docker images
      run: |
        bash scripts/build-image.sh

    # Launch temporary EC2
    - name: Launch temporary EC2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
          --image-id ${{ secrets.AMI_ID }} \
          --instance-type t2.micro \
          --security-group-ids $EC2_SECURITY_GROUP \
          --subnet-id $EC2_SUBNET \
          --associate-public-ip-address \
          --key-name $EC2_KEY_NAME \
          --user-data file://scripts/userdata.sh \
          --query 'Instances[0].InstanceId' \
          --output text)

        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

        aws ec2 wait instance-running --instance-ids $INSTANCE_ID

        EC2_IP=$(aws ec2 describe-instances \
          --instance-ids $INSTANCE_ID \
          --query 'Reservations[0].Instances[0].PublicIpAddress' \
          --output text)

        echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

        echo "Temporary EC2 IP: $EC2_IP"

   # Set up ssh 
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

   # Wait for EC2
    - name: Wait for EC2 Initialization
      run: |
        echo "Waiting for EC2..."

        for i in {1..30}; do
          if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ec2-user@$EC2_IP "echo connected"; then
            echo "EC2 is ready"
            break
          fi
          echo "Waiting for SSH..."
          sleep 10
        done
        
        ssh -o StrictHostKeyChecking=no ec2-user@$EC2_IP \
        "while [ ! -f /var/lib/cloud/instance/boot-finished ]; do echo waiting...; sleep 5; done"

    # Transfer images
    - name: Run containers on EC2
      run: |
        docker save spa-backend | ssh -o StrictHostKeyChecking=no ec2-user@$EC2_IP "sudo docker load"
        docker save spa-frontend | ssh -o StrictHostKeyChecking=no ec2-user@$EC2_IP "sudo docker load"
        
        scp -o StrictHostKeyChecking=no spa-app/docker-compose.deploy.yml ec2-user@$EC2_IP:docker-compose.yml

        ssh -o StrictHostKeyChecking=no ec2-user@$EC2_IP << EOF

        cat <<ENV > .env
        MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        DB_URL=${{ secrets.DB_URL }}
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        ENV

        cat .env

        sudo docker-compose up -d

        sudo docker ps
        sudo docker images

        sudo docker logs ec2-user-backend-1 --tail 50
        sudo docker logs ec2-user-frontend-1 --tail 50

        EOF

    # smoke test
    - name: Smoke test
      run: |
        bash scripts/smoke-test.sh
      env:
        EC2_IP: ${{env.EC2_IP}}

    # Terminate temp EC2
    - name: Terminate temporary EC2
      if: always()
      run: |
        if [ -n "$INSTANCE_ID" ]; then
          aws ec2 terminate-instances --instance-ids $INSTANCE_ID
        fi

    # Push images to ECR
    - name: Push images to ECR
      run: |
        bash scripts/push-ecr.sh

    # Deploy to QA
    - name: Deploy to QA EC2
      run: | 
        bash scripts/deploy-qa.sh ${{ secrets.QA_EC2_IP }} ${{ secrets.ECR_REPO }}
